server:
  port: 8071
  servlet:
    context-path: /

logging.level:
  org.apache.kafka: ERROR

info:
  name: '@project.name@'
  version: '@project.version@'
  description: '@project.description@'

spring:
  data:
    arangodb:
      user: root
      password: openSesame
      database: people

kafka:
  bootstrap-servers: localhost:9092
  topic:
    request: request-person
    response: response-person
  group: api